feature.file.encoding=UTF-8
webdriver.timeouts.implicitlywait = 20000
webdriver.driver = appium

appium.app =
appium.platformVersion =
appium.deviceName =
appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.automationName = uiautomator2
appium.appPackage =
appium.appActivity =
appium.autoGrantPermissions=true

serenity.dry.run=false
serenity.test.root=net.thucydides.showcase.cucumber.junit
serenity.report.encoding=UTF-8
serenity.take.screenshots.for.tasks=AFTER_EACH_STEP
serenity.take.screenshots.for.interactions=FOR_FAILURES
serenity.take.screenshots.for.questions=BEFORE_AND_AFTER_EACH_STEP